package EmployeeUI;

import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import business.*;
import java.lang.reflect.Method;
import java.util.*;
/**
 *
 * @author soung
 */
public class EmployeeUI extends javax.swing.JFrame {
String filename;
Map<Long,Employee> emps;
Map<String,Employee> empbyname; //declare variable
Map<String,JTextField> screenmap;//declare screenmap
String[] getMethods={"getEmployeeNumber","getFirstName","getLastName","getMiddleName"
        ,"getSuffix","getAddress1","getAddress2","getCity","getState","getZip"
        ,"getPhone","getGender","getPayCode","getStatus","getHireDate","getTerminationDate"
}; //all getters from employee
JTextField[] fields; //housekipping store method, declare array-모두 하나씩 해줄수 없으므로
int loading = 0;//  indicator. 0 is not loading(add, delete등 update가능). 1 is loading(update불가능).
//              로컬아닌 클래스레벨에서 만들어줌
    
    public EmployeeUI() {
        initComponents();
//        disableButtons(); //맨처음 들어갔을때 3가지메뉴 사용못하게해줌
        JTextField[] flds={jTextFieldEmpNo, jTextFieldFirstnm, jTextFieldLastnm,
            jTextFieldMiddlenm, jTextFieldSuffix, jTextFieldAddr1, jTextFieldAddr2,
            jTextFieldCity, jTextFieldState, jTextFieldZip, jTextFieldPhone, jTextFieldGender,
            jTextFieldPaycd, jTextFieldStatus, jTextFieldHiredt, jTextFieldTermdt
        };//initiate constructor
        fields=flds;
        screenmap=new HashMap<>();
       // associate combo box key with jTextFields
       for (int i=0; i<getMethods.length; i++){
           screenmap.put(getMethods[i],fields[i]);
       }
    }
    private void displayValues(Employee e) {// 여기서는 public과 별차이 없음. 
        //clear all jTextFields
        clearFields(); //clearField method만들어주기
        //use java.lang.reflection package *****중요한부분***************************
        Class empClass=e.getClass();//starting point for using reflection
        Method[] methods=empClass.getMethods(); //Method class is obtained from Class
        try{
            for(Method m: methods){
                if(screenmap.containsKey((m.getName()))){ //ensure field exists in screenmap
                    JTextField field=screenmap.get(m.getName()); //obtain target field
                    switch (m.getName()) {
                        case "getEmployeeNumber":
                            long x=(long)m.invoke(e,null);
                            field=screenmap.get(m.getName());
                            field.setText((String.valueOf(x)));//conversion
                            break;
                        case "getPhone":
                            int y=(int)m.invoke(e,null);
                            field=screenmap.get(m.getName());
                            field.setText((String.valueOf(y)));
                            break;
                        case "getPayCode":
                            int z=(int)m.invoke(e,null);
                            field=screenmap.get(m.getName());
                            field.setText((String.valueOf(z)));
                            break;
                        default://EmpNuo,phone,paycode외에 나머지는 다 default
                            if (String.valueOf(m.invoke(e, null)).equals("null")){
                            field.setText("");
                            }
                            else {
                                    field.setText(String.valueOf(m.invoke(e, null)));
                            }
                            break;
                    }
                }
            }
        }
        catch(Exception ex) { //이거 넣으면 위의 case의 에러들이 사라져야함
            ex.printStackTrace();
        }
    }
    private void clearFields(){
        for (JTextField fld:fields){
            fld.setText("");
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jRadioButtonRaw = new javax.swing.JRadioButton();
        jRadioButtonEmpno = new javax.swing.JRadioButton();
        jRadioButtonName = new javax.swing.JRadioButton();
        jButtonPrevious = new javax.swing.JButton();
        jComboBoxEmployee = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jButtonNext = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldEmpNo = new javax.swing.JTextField();
        jTextFieldLastnm = new javax.swing.JTextField();
        jTextFieldMiddlenm = new javax.swing.JTextField();
        jTextFieldFirstnm = new javax.swing.JTextField();
        jTextFieldSuffix = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldAddr1 = new javax.swing.JTextField();
        jTextFieldAddr2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldCity = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldState = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldZip = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldPhone = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldGender = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextFieldPaycd = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextFieldStatus = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextFieldHiredt = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextFieldTermdt = new javax.swing.JTextField();
        jLabelMessage = new javax.swing.JLabel();
        jButtonAddNew = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonSave = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonExit = new javax.swing.JButton();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenuFile = new javax.swing.JMenu();
        jMenuItemLoadCSV = new javax.swing.JMenuItem();
        jMenuItemExit = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(jRadioButtonRaw);
        jRadioButtonRaw.setText("Raw HashMap w.Empno Key");
        jRadioButtonRaw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonRawActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonEmpno);
        jRadioButtonEmpno.setText("TreeMap by Empno");
        jRadioButtonEmpno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonEmpnoActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButtonName);
        jRadioButtonName.setText("Map with Name Key (sorted)");
        jRadioButtonName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonNameActionPerformed(evt);
            }
        });

        jButtonPrevious.setText("<-");
        jButtonPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPreviousActionPerformed(evt);
            }
        });

        jComboBoxEmployee.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxEmployeeItemStateChanged(evt);
            }
        });
        jComboBoxEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxEmployeeActionPerformed(evt);
            }
        });

        jLabel1.setText("Employees:");

        jButtonNext.setText("->");
        jButtonNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNextActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("EmpNo:");

        jLabel3.setText("Name: Last");

        jLabel4.setText("First");

        jLabel5.setText("Mid");

        jLabel6.setText("Suffix");

        jLabel7.setText("Addr:");

        jLabel8.setText("City:");

        jLabel9.setText("State:");

        jLabel10.setText("Zip:");

        jLabel11.setText("Phone:");

        jLabel12.setText("Gender:");

        jTextFieldGender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldGenderActionPerformed(evt);
            }
        });

        jLabel13.setText("Pay Cd:");

        jLabel14.setText("Status:");

        jLabel15.setText("Hire Date:");

        jLabel16.setText("Terminate Date:");

        jLabelMessage.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelMessage.setText("Select a file to load first.");

        jButtonAddNew.setText("Add New Employee");
        jButtonAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddNewActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonUpdate.setText("Update");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonSave.setText("Save");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonClear.setText("Clear");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonExit.setText("Exit");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextFieldEmpNo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextFieldLastnm, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldFirstnm, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(19, 19, 19)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldMiddlenm, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldSuffix, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldAddr2, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                                .addComponent(jTextFieldAddr1))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldGender, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldState, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10)
                                .addGap(26, 26, 26)
                                .addComponent(jTextFieldZip, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(21, 21, 21))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonAddNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonDelete)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonClear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonExit))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addComponent(jLabelMessage))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldHiredt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldTermdt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(13, 13, 13)
                        .addComponent(jTextFieldPaycd, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextFieldSuffix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldEmpNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldLastnm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldFirstnm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldMiddlenm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jTextFieldAddr1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldAddr2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jTextFieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextFieldState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldGender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jTextFieldPaycd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTextFieldStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(jTextFieldHiredt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(jTextFieldTermdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelMessage)
                        .addContainerGap(71, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAddNew)
                            .addComponent(jButtonDelete)
                            .addComponent(jButtonUpdate)
                            .addComponent(jButtonSave)
                            .addComponent(jButtonClear)
                            .addComponent(jButtonExit))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jButtonPrevious)
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1))
                    .addComponent(jRadioButtonRaw))
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadioButtonEmpno)
                    .addComponent(jComboBoxEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jRadioButtonName)
                        .addContainerGap(29, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonNext)
                        .addGap(86, 86, 86))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonRaw)
                    .addComponent(jRadioButtonEmpno)
                    .addComponent(jRadioButtonName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBoxEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNext)
                    .addComponent(jButtonPrevious))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jMenuFile.setText("File");

        jMenuItemLoadCSV.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemLoadCSV.setText("Load CSV");
        jMenuItemLoadCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemLoadCSVActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemLoadCSV);

        jMenuItemExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItemExit.setText("Exit");
        jMenuItemExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemExitActionPerformed(evt);
            }
        });
        jMenuFile.add(jMenuItemExit);

        jMenuBar3.add(jMenuFile);

        jMenu6.setText("Edit");
        jMenuBar3.add(jMenu6);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPreviousActionPerformed
        //move to previous record. diplay a message if you are already on the first reord
        
        if(!(jComboBoxEmployee.getSelectedIndex()<=0)){            
                jComboBoxEmployee.setSelectedIndex(jComboBoxEmployee.getSelectedIndex()-1);
        }
        else {
            jLabelMessage.setText("You are already on the first record. ");
        }
    }//GEN-LAST:event_jButtonPreviousActionPerformed

    private void jTextFieldGenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldGenderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldGenderActionPerformed

    private void jComboBoxEmployeeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxEmployeeItemStateChanged
        //ensure record loading is completed
        if(loading==1){
            return;
        }
        if(jComboBoxEmployee.getSelectedIndex()==-1){// no employee is selected
            jLabelMessage.setText("No record is selected. Select a record. ");
            return;
          
        }
        else {  //**이해가안감
            Employee e;
            if(jRadioButtonName.isSelected()) {
                e=(Employee) empbyname.get((String)jComboBoxEmployee.getSelectedItem());
            }
            else {
                e=(Employee) emps.get((Long)jComboBoxEmployee.getSelectedItem());
            }
            //update display values
            String recordinfo="You are viewing record for ";
            displayValues(e);
            if(String.valueOf(e.getMiddleName()).equals("null")){
                jTextFieldMiddlenm.setText("");//null대신 빈칸으로 보이게
                recordinfo+=e.getLastName()+", "+e.getFirstName();
            }
            else {
                recordinfo+=e.getLastName()+", "+e.getFirstName()+" "
                        +e.getMiddleName();
                
            }
            jLabelMessage.setText(recordinfo);
        }
    }//GEN-LAST:event_jComboBoxEmployeeItemStateChanged

    private void jRadioButtonEmpnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonEmpnoActionPerformed
        try{
            if(jRadioButtonRaw.isSelected())
            buildComboBox();
            jLabelMessage.setText("TreeMap populated. Select an employee"
                    +" number to display employee information");
            loading = 0;
        }
        catch(NullPointerException ex){
            jLabelMessage.setText("Error occured, no record loaded. Select a file to load");
            jMenuFile.doClick();
        }
        buildComboBox();

        
    }//GEN-LAST:event_jRadioButtonEmpnoActionPerformed

    private void jRadioButtonRawActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonRawActionPerformed
        // call buildComboBox() method
//        buildComboBox();
        try{
            if(jRadioButtonRaw.isSelected())
            buildComboBox();
            jLabelMessage.setText("Raw HashMap populated. Selected an employee"
                + " number to display employee information");
            loading = 0;
        }
        catch (NullPointerException ex){
            jLabelMessage.setText("Error occurred, no record loaded. Select a file to");
            jMenuFile.doClick();
            buttonGroup1.clearSelection();//안해주면 파일선택전에 3가지 메뉴 먼저선택시 위의 에러메시지나오고
                                         //파일선택후 3가지메뉴 선택해도 그전에 클릭했던것이 남아 혼돈되므로 
                                         //이 메소드써주면 실수해도 그전의 3가지 중 하나 클릭한게 지워짐 
            
        }
    }//GEN-LAST:event_jRadioButtonRawActionPerformed

    private void jMenuItemExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemExitActionPerformed
         System.exit(0);
    }//GEN-LAST:event_jMenuItemExitActionPerformed

    private void jMenuItemLoadCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemLoadCSVActionPerformed
        //declare a FileChooser
        JFileChooser f=new JFileChooser(".");  //display current directory(project folder) //import  javax.swing.*;해줘야함
        f.setDialogTitle("Select Employee File");
        FileNameExtensionFilter filter=new FileNameExtensionFilter("CSV file(*.csv"
                                       ,"CSV");
        f.setFileFilter(filter); //filter for CSV files
        JDialog jd=new JDialog();
        int val=f.showOpenDialog(jd);
        if (val==JFileChooser.CANCEL_OPTION){
            jLabelMessage.setText("open operation canceled");
        }
        else{
            filename=f.getSelectedFile().getAbsolutePath(); //이해가 안감
            emps=EmployeeIO.getEmployees(filename);//맨윗쪽에보면 Map<Long,Employee>볼수있음//EmployeeIO에는 getEmployees method 하나밖에없음
            jLabelMessage.setText(String.valueOf(emps.size())+" records found");
        }
        enableButtons();
    }//GEN-LAST:event_jMenuItemLoadCSVActionPerformed
    private void enableButtons(){
        jRadioButtonRaw.setEnabled(true);
        jRadioButtonEmpno.setEnabled(true);
        jRadioButtonName.setEnabled(true);
    }
    private void disableButtons(){
        jRadioButtonRaw.setEnabled(false);//맨처음들어갔을때 위3개 클릭못하게
        jRadioButtonEmpno.setEnabled(false);
        jRadioButtonName.setEnabled(false);
    }
            
    private void jRadioButtonNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonNameActionPerformed
        // essence if from treeMap
        try{
            if(jRadioButtonRaw.isSelected())
            buildComboBox();
            jLabelMessage.setText("Map with name key populated. Select an employee"
                    +" number to display employee information");
            loading = 0;
        }
        catch(NullPointerException ex){
            jLabelMessage.setText("Error occured, no record loaded. Select a file to load");
            jMenuFile.doClick();
        }
        
        buildComboBox(); 
    }//GEN-LAST:event_jRadioButtonNameActionPerformed

    private void jComboBoxEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxEmployeeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxEmployeeActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
            
   
        
        
        
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        //make sure there is a file loaded
        if(filename==null) {
            JOptionPane.showMessageDialog(null, "Please load a file first"
            +"attemping to udate employee recoreds!","File not found", JOptionPane.ERROR_MESSAGE);
            return;
        }
        else if (jComboBoxEmployee.getSelectedIndex()==-1){
            JOptionPane.showConfirmDialog(null, "Please select an employee"
            +" before attempting to update", "No employee selected", JOptionPane.ERROR_MESSAGE);
            return;
        }
        Long empnum=Long.parseLong(jTextFieldEmpNo.getText());
        String deleteEmp=emps.get(empnum).getFullName();
        if (emps.containsKey(empnum)){
            int confirm = JOptionPane.showConfirmDialog(null, 
                    "Are you sure you would like to delete this employee? \n\n"
                +"employee from the Employee records? \n\n"
                +"******************* THIS CANNOT BE UNDONE******************** \n\n"
                +"Employee Number: "+ empnum.toString()+"\n"
                +"Employee Name: "+emps.get(empnum).getFullName(), "Confirm Delete",
                 JOptionPane.YES_NO_OPTION); //4 argument parameter
            if (confirm==JOptionPane.YES_OPTION) { //지우겠습니까? 예하면 정보지워짐
                emps.remove(empnum); //only remove the record in the map(완전지워지는것이 아님 Map에서만)-그래서 다시 파일에서 찾아서 reload하면 다시 나타남.disc에는 남아있으므로
                clearFields();
                buildComboBox();
                jLabelMessage.setText("Employee '"+deleteEmp
                        +"' deleted. Click Save to make the change permanent");
            }
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        //call EmployeeIO.setEmps() method
        jLabelMessage.setText(EmployeeIO.setEmps(filename, emps)); //EmployeeIO 에 setEmps method만든후 작성
                                                                   //*****이 코드 작성후 delete로 employee 지우고 난후 save 누르면 그이후로 100명이 아닌 99명이 나온다. 완전히 지워진것. 
    }//GEN-LAST:event_jButtonSaveActionPerformed

    private void jButtonNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNextActionPerformed
         //move to next record. diplay a message if you are already on the first reord
        
        if(!(jComboBoxEmployee.getSelectedIndex()<=0)){            
                jComboBoxEmployee.setSelectedIndex(jComboBoxEmployee.getSelectedIndex()+1);
        }
        else {
            jLabelMessage.setText("You are already on the last record. ");
        }
    }//GEN-LAST:event_jButtonNextActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // call clearValues()
        clearFields();
        buttonGroup1.clearSelection();
        jComboBoxEmployee.removeAllItems();
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddNewActionPerformed
        
        
        
        
        
    }//GEN-LAST:event_jButtonAddNewActionPerformed

    public void buildComboBox(){//만들어야함.전체가 이해가안감 1:08분지점 설명
        loading=1; //loading. 처음에 0으로초기화하고 내가 로딩했을때 1부터(update불가능)볼수있게
        jComboBoxEmployee.removeAllItems();//이미 아이템이 있으면 다 지워야하므로
        if (jRadioButtonRaw.isSelected()) { 
            HashMap<Long,Employee> hashmap=new HashMap<>(emps); //key(employee No),value값 
            for(Map.Entry<Long,Employee>entry:hashmap.entrySet()){
                Long k=entry.getKey();
                jComboBoxEmployee.addItem(k);
            }
        }
        else if(jRadioButtonEmpno.isSelected()){
            TreeMap<Long,Employee> treemap=new TreeMap<>(emps);
            for(Map.Entry<Long,Employee> entry:treemap.entrySet()){
                Long k=entry.getKey();
                jComboBoxEmployee.addItem(k);
            }
        }
       else if(jRadioButtonName.isSelected()){
           empbyname=new TreeMap<>();
           for(Map.Entry<Long,Employee> entry:emps.entrySet()){
               Employee e=entry.getValue();
               String name=e.getLastName()+", "+e.getFirstName()
                       +" "+e.getMiddleName();
               empbyname.put(name,e);
           }
           for (Map.Entry<String,Employee> entry:empbyname.entrySet()){
               String k=entry.getKey();
               jComboBoxEmployee.addItem(k);
           }
       }
        jComboBoxEmployee.setSelectedIndex(-1); //아무것도 선택 안되게 -1로.
        loading=0; //not loading(update가능)으로 다시 돌아가야함
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonAddNew;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonExit;
    private javax.swing.JButton jButtonNext;
    private javax.swing.JButton jButtonPrevious;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JComboBox jComboBoxEmployee;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabelMessage;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenu jMenuFile;
    private javax.swing.JMenuItem jMenuItemExit;
    private javax.swing.JMenuItem jMenuItemLoadCSV;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButtonEmpno;
    private javax.swing.JRadioButton jRadioButtonName;
    private javax.swing.JRadioButton jRadioButtonRaw;
    private javax.swing.JTextField jTextFieldAddr1;
    private javax.swing.JTextField jTextFieldAddr2;
    private javax.swing.JTextField jTextFieldCity;
    private javax.swing.JTextField jTextFieldEmpNo;
    private javax.swing.JTextField jTextFieldFirstnm;
    private javax.swing.JTextField jTextFieldGender;
    private javax.swing.JTextField jTextFieldHiredt;
    private javax.swing.JTextField jTextFieldLastnm;
    private javax.swing.JTextField jTextFieldMiddlenm;
    private javax.swing.JTextField jTextFieldPaycd;
    private javax.swing.JTextField jTextFieldPhone;
    private javax.swing.JTextField jTextFieldState;
    private javax.swing.JTextField jTextFieldStatus;
    private javax.swing.JTextField jTextFieldSuffix;
    private javax.swing.JTextField jTextFieldTermdt;
    private javax.swing.JTextField jTextFieldZip;
    // End of variables declaration//GEN-END:variables
}
